
project_id = "etgkuasmqjidwtaxrfww"

[api]
port = 8080

[auth]
site_url = "https://tcgupdates.com"
additional_redirect_urls = ["https://www.tcgupdates.com"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.smtp]
sender_name = "TCG Updates"
sender_email = "noreply@tcgupdates.com"

[auth.external.email]
enabled = true

[auth.external]
apple.enabled = false
azure.enabled = false
bitbucket.enabled = false
discord.enabled = false
facebook.enabled = false
github.enabled = false
gitlab.enabled = false
google.enabled = false
keycloak.enabled = false
linkedin.enabled = false
notion.enabled = false
spotify.enabled = false
slack.enabled = false
twitch.enabled = false
twitter.enabled = false
workos.enabled = false
zoom.enabled = false
