
project_id = "etgkuasmqjidwtaxrfww"

[api]
port = 8080

[auth]
site_url = "https://tcgupdates.com"
additional_redirect_urls = ["https://www.tcgupdates.com"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# External email provider configuration
[auth.email.template.provider]
enabled = true
url = "https://etgkuasmqjidwtaxrfww.supabase.co/functions/v1/custom-email"

# Sender information - moved to correct location
[auth.smtp]
sender_name = "TCG Updates"
sender_email = "noreply@tcgupdates.com"
