
# Project ID should remain as the first line
project_id = "etgkuasmqjidwtaxrfww"

[api]
port = 8080

[auth]
site_url = "https://tcgupdates.com"
additional_redirect_urls = ["https://www.tcgupdates.com", "http://localhost:5173", "http://localhost:3000"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Password reset configuration in the proper format
[auth.email.password_recovery]
enable = true

[auth.email.smtp]
sender_name = "TCG Updates"
admin_email = "noreply@tcgupdates.com"
host = "smtp.sendgrid.net"
port = 587
user = "apikey"
pass = "SMTP_PASSWORD"

[auth.external.apple]
enabled = false

[auth.external.azure]
enabled = false

[auth.external.bitbucket]
enabled = false

[auth.external.discord]
enabled = false

[auth.external.facebook]
enabled = false

[auth.external.github]
enabled = false

[auth.external.gitlab]
enabled = false

[auth.external.google]
enabled = true
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false

[auth.external.linkedin]
enabled = false

[auth.external.notion]
enabled = false

[auth.external.spotify]
enabled = false

[auth.external.slack]
enabled = false

[auth.external.twitch]
enabled = false

[auth.external.twitter]
enabled = false

[auth.external.workos]
enabled = false

[auth.external.zoom]
enabled = false

[auth.external.email]
enabled = true
client_id = "email"
secret = "email"

[functions]
# Fix the import_map_path to be properly formatted
import_map_path = "supabase/import_map.json"

# Fix the HTTP functions format with proper mapping
[[functions.http]]
path = "/handle-inbound-email"
verify_jwt = false
