
project_id = "etgkuasmqjidwtaxrfww"

[api]
port = 8080

[auth]
site_url = "https://tcgupdates.com"
additional_redirect_urls = ["https://www.tcgupdates.com"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Correct format for external email provider
[auth.external.email.template]
provider = {
  enabled = true,
  url = "https://etgkuasmqjidwtaxrfww.supabase.co/functions/v1/custom-email"
}

# SMTP configuration - must be at the root level
[smtp]
sender_name = "TCG Updates"
sender_email = "noreply@tcgupdates.com"
