
[build]
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/proxy-sitemap?type=all"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-static.xml"
  to = "/.netlify/functions/proxy-sitemap?type=static"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-articles.xml"
  to = "/.netlify/functions/proxy-sitemap?type=articles"
  status = 200
  force = true

[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"
