// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etgkuasmqjidwtaxrfww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0Z2t1YXNtcWppZHd0YXhyZnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Mjc2MzAsImV4cCI6MjA1NjMwMzYzMH0.X9Ree_fRi2AquK60dhrmeYk4eC5JF05ThE0uBJJVfEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);